05-27 14:26:24 jdbc[3]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.message.DbException.get(DbException.java:143)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:74)
	at org.netbeans.modules.db.explorer.DbDriverManager.getConnection(DbDriverManager.java:131)
	at org.netbeans.modules.db.explorer.DatabaseConnection.doConnect(DatabaseConnection.java:904)
	at org.netbeans.modules.db.explorer.DatabaseConnection.access$200(DatabaseConnection.java:103)
	at org.netbeans.modules.db.explorer.DatabaseConnection$3.run(DatabaseConnection.java:970)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	... 13 more
05-27 14:27:33 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:27:33 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:27:33 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:27:37 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:28:15 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "USE[*] FITNESSXTREME "; expected "UPDATE, {"; SQL statement:
USE FitnessXtreme [42001-176]
05-27 14:28:36 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Schema "FITNESSXTREME" already exists; SQL statement:
CREATE SCHEMA FitnessXtreme [90078-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.command.ddl.CreateSchema.update(CreateSchema.java:49)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:186)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper.executeSQLStatement(SQLExecutionHelper.java:869)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper.access$500(SQLExecutionHelper.java:84)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper$1Loader.run(SQLExecutionHelper.java:145)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
05-27 14:28:49 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:28:49 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:28:49 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:28:50 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:08 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:08 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:08 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:08 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:08 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:11 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:12 jdbc[6]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:101)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:119)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:74)
	at org.netbeans.modules.db.explorer.DbDriverManager.getConnection(DbDriverManager.java:131)
	at org.netbeans.modules.db.explorer.DatabaseConnection.doConnect(DatabaseConnection.java:904)
	at org.netbeans.modules.db.explorer.DatabaseConnection.access$200(DatabaseConnection.java:103)
	at org.netbeans.modules.db.explorer.DatabaseConnection$3.run(DatabaseConnection.java:970)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.message.DbException.get(DbException.java:143)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:74)
	at org.netbeans.modules.db.explorer.DbDriverManager.getConnection(DbDriverManager.java:131)
	at org.netbeans.modules.db.explorer.DatabaseConnection.doConnect(DatabaseConnection.java:904)
	at org.netbeans.modules.db.explorer.DatabaseConnection.access$200(DatabaseConnection.java:103)
	at org.netbeans.modules.db.explorer.DatabaseConnection$3.run(DatabaseConnection.java:970)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	... 13 more
05-27 14:29:35 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:35 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:35 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:35 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:36 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:36 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:36 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:56 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:56 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:56 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:58 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:48:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unknown data type: "FK_AULAUSUARIO_IDX"; SQL statement:
CREATE TABLE  FitnessXtreme.Aula (
  idAula INT NOT NULL,
  Objetivo VARCHAR(200) NOT NULL,
  descAula VARCHAR(100),
  Usuario_idUsuario INT NOT NULL,
  dataInicioSerie DATE NOT NULL,
  dataFimSerie DATE NOT NULL,
  observacao VARCHAR(200) NOT NULL,
  dataAula DATE NOT NULL,
  repetirToda VARCHAR(50) NOT NULL,
  tempoEsteira VARCHAR(10),
  tempoBicicleta VARCHAR(10),
  tempoElipticon VARCHAR(10),
  PRIMARY KEY (idAula),
  INDEX fk_AulaUsuario_idx (Usuario_idUsuario ASC),
  CONSTRAINT fk_AulaUsuario
    FOREIGN KEY (Usuario_idUsuario)
    REFERENCES FitnessXtreme.Usuario (idUsuario)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION) [50004-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:3963)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3826)
	at org.h2.command.Parser.parseCreateTable(Parser.java:5723)
	at org.h2.command.Parser.parseCreate(Parser.java:4122)
	at org.h2.command.Parser.parsePrepared(Parser.java:351)
	at org.h2.command.Parser.parse(Parser.java:306)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.prepareCommand(Parser.java:243)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper.executeSQLStatement(SQLExecutionHelper.java:869)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper.access$500(SQLExecutionHelper.java:84)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper$1Loader.run(SQLExecutionHelper.java:145)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
05-27 14:48:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unknown data type: "FK_EXERCICIO_GURPOEXERCICIO_IDX"; SQL statement:
CREATE TABLE  FitnessXtreme.Exercicio (
  idExercicio INT NOT NULL,
  nomeExercicio VARCHAR(100) NOT NULL,
  GurpoExercicio_idGurpoExercicio INT NOT NULL,
  PRIMARY KEY (idExercicio),
  INDEX fk_Exercicio_GurpoExercicio_idx (GurpoExercicio_idGurpoExercicio ASC),
  CONSTRAINT fk_Exercicio_GurpoExercicio
    FOREIGN KEY (GurpoExercicio_idGurpoExercicio)
    REFERENCES FitnessXtreme.GurpoExercicio (idGurpoExercicio)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION) [50004-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:3963)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3826)
	at org.h2.command.Parser.parseCreateTable(Parser.java:5723)
	at org.h2.command.Parser.parseCreate(Parser.java:4122)
	at org.h2.command.Parser.parsePrepared(Parser.java:351)
	at org.h2.command.Parser.parse(Parser.java:306)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.prepareCommand(Parser.java:243)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper.executeSQLStatement(SQLExecutionHelper.java:869)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper.access$500(SQLExecutionHelper.java:84)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper$1Loader.run(SQLExecutionHelper.java:145)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
05-27 14:48:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unknown data type: "FK_EXERCICIOPESO_PESO_IDX"; SQL statement:
CREATE TABLE  FitnessXtreme.ExercicioPeso (
  idExercicio INT NOT NULL,
  idPeso INT NOT NULL,
  PRIMARY KEY (idExercicio, idPeso),
  INDEX fk_ExercicioPeso_Peso_idx (idPeso ASC),
  INDEX fk_ExercicioPeso_Exercicio_idx (idExercicio ASC),
  CONSTRAINT fk_ExercicioPeso_Exercicio
    FOREIGN KEY (idExercicio)
    REFERENCES FitnessXtreme.Exercicio (idExercicio)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_ExercicioPeso_Peso
    FOREIGN KEY (idPeso)
    REFERENCES FitnessXtreme.Peso (idPeso)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION) [50004-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:3963)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3826)
	at org.h2.command.Parser.parseCreateTable(Parser.java:5723)
	at org.h2.command.Parser.parseCreate(Parser.java:4122)
	at org.h2.command.Parser.parsePrepared(Parser.java:351)
	at org.h2.command.Parser.parse(Parser.java:306)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.prepareCommand(Parser.java:243)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper.executeSQLStatement(SQLExecutionHelper.java:869)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper.access$500(SQLExecutionHelper.java:84)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper$1Loader.run(SQLExecutionHelper.java:145)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
05-27 14:48:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unknown data type: "FK_EXERCICIOSERIE_SERIE_IDX"; SQL statement:
CREATE TABLE  FitnessXtreme.ExercicioSerie (
  idExercicio INT NOT NULL,
  idSerie INT NOT NULL,
  PRIMARY KEY (idExercicio, idSerie),
  INDEX fk_ExercicioSerie_Serie_idx (idSerie ASC),
  INDEX fk_ExercicioSerie_Exercicio_idx (idExercicio ASC),
  CONSTRAINT fk_ExercicioSerie_Exercicio
    FOREIGN KEY (idExercicio)
    REFERENCES FitnessXtreme.Exercicio (idExercicio)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_ExercicioSerie_Serie
    FOREIGN KEY (idSerie)
    REFERENCES FitnessXtreme.Serie (idSerie)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION) [50004-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:3963)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3826)
	at org.h2.command.Parser.parseCreateTable(Parser.java:5723)
	at org.h2.command.Parser.parseCreate(Parser.java:4122)
	at org.h2.command.Parser.parsePrepared(Parser.java:351)
	at org.h2.command.Parser.parse(Parser.java:306)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.prepareCommand(Parser.java:243)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper.executeSQLStatement(SQLExecutionHelper.java:869)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper.access$500(SQLExecutionHelper.java:84)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper$1Loader.run(SQLExecutionHelper.java:145)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
05-27 14:48:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unknown data type: "FK_AULAEXERCICIO_EXERCICIO_IDX"; SQL statement:
CREATE TABLE  FitnessXtreme.AulaExercicio (
  idAula INT NOT NULL,
  idExercicio INT NOT NULL,
  PRIMARY KEY (idAula, idExercicio),
  INDEX fk_AulaExercicio_Exercicio_idx (idExercicio ASC),
  INDEX fk_AulaExercicio_Aula_idx (idAula ASC),
  CONSTRAINT fk_AulaExercicio_Aula
    FOREIGN KEY (idAula)
    REFERENCES FitnessXtreme.Aula (idAula)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_AulaExercicio_Exercicio
    FOREIGN KEY (idExercicio)
    REFERENCES FitnessXtreme.Exercicio (idExercicio)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION) [50004-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:3963)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3826)
	at org.h2.command.Parser.parseCreateTable(Parser.java:5723)
	at org.h2.command.Parser.parseCreate(Parser.java:4122)
	at org.h2.command.Parser.parsePrepared(Parser.java:351)
	at org.h2.command.Parser.parse(Parser.java:306)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.prepareCommand(Parser.java:243)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper.executeSQLStatement(SQLExecutionHelper.java:869)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper.access$500(SQLExecutionHelper.java:84)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper$1Loader.run(SQLExecutionHelper.java:145)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
05-27 14:49:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "FITNESSXTREME" not found; SQL statement:
drop TABLE FITNESSXTREME [42102-176]
05-27 14:52:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "CREATE TABLE  FITNESSXTREME.USUARIO (
  IDUSUARIO INT NOT NULL,
  NOME VARCHAR(100) NOT NULL,
  MATRICULA INT NOT NULL,
  DATANASCIMENTO DATE NOT NULL,
  CPF VARCHAR(45),
  INDICADORDIREITO VARCHAR(1000) NOT NULL,
  INDICADORESQUERDO VARCHAR(1000) NOT NULL,
  SENHA VARCHAR(50),
  DATACADASTRAMENTO DATE NOT NULL,
  EADMINISTRADOR SMALLINT(1) NOT NULL,
  PRIMARY KEY (IDUSUARIO) "; expected "INDEX, ,, )"; SQL statement:
CREATE TABLE  FitnessXtreme.Usuario (
  idUsuario INT NOT NULL,
  nome VARCHAR(100) NOT NULL,
  matricula INT NOT NULL,
  dataNascimento DATE NOT NULL,
  cpf VARCHAR(45),
  indicadorDireito VARCHAR(1000) NOT NULL,
  indicadorEsquerdo VARCHAR(1000) NOT NULL,
  senha VARCHAR(50),
  dataCadastramento DATE NOT NULL,
  eAdministrador SMALLINT(1) NOT NULL,
  PRIMARY KEY (idUsuario) [42001-176]
05-27 14:52:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USUARIO" not found; SQL statement:
CREATE TABLE  FitnessXtreme.Aula (
  idAula INT NOT NULL,
  Objetivo VARCHAR(200) NOT NULL,
  descAula VARCHAR(100),
  Usuario_idUsuario INT NOT NULL,
  dataInicioSerie DATE NOT NULL,
  dataFimSerie DATE NOT NULL,
  observacao VARCHAR(200) NOT NULL,
  dataAula DATE NOT NULL,
  repetirToda VARCHAR(50) NOT NULL,
  tempoEsteira VARCHAR(10),
  tempoBicicleta VARCHAR(10),
  tempoElipticon VARCHAR(10),
  PRIMARY KEY (idAula),  
  CONSTRAINT fk_AulaUsuario
    FOREIGN KEY (Usuario_idUsuario)
    REFERENCES FitnessXtreme.Usuario (idUsuario)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION) [42102-176]
05-27 14:52:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "AULA" not found; SQL statement:
CREATE TABLE  FitnessXtreme.AulaExercicio (
  idAula INT NOT NULL,
  idExercicio INT NOT NULL,
  PRIMARY KEY (idAula, idExercicio),
  CONSTRAINT fk_AulaExercicio_Aula
    FOREIGN KEY (idAula)
    REFERENCES FitnessXtreme.Aula (idAula)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_AulaExercicio_Exercicio
    FOREIGN KEY (idExercicio)
    REFERENCES FitnessXtreme.Exercicio (idExercicio)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION) [42102-176]
05-27 15:19:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "EXERCICIO" not found; SQL statement:
CREATE TABLE  FitnessXtreme.ExercicioSerie (
  idExercicio INT NOT NULL AUTO_INCREMENT,
  idSerie INT NOT NULL,
  PRIMARY KEY (idExercicio, idSerie),
  CONSTRAINT fk_ExercicioSerie_Exercicio
    FOREIGN KEY (idExercicio)
    REFERENCES FitnessXtreme.Exercicio (idExercicio)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_ExercicioSerie_Serie
    FOREIGN KEY (idSerie)
    REFERENCES FitnessXtreme.Serie (idSerie)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION) [42102-176]
05-27 15:20:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "EXERCICIO" not found; SQL statement:
CREATE TABLE  FitnessXtreme.ExercicioSerie (
  idExercicio INT NOT NULL AUTO_INCREMENT,
  idSerie INT NOT NULL,
  PRIMARY KEY (idExercicio, idSerie),
  CONSTRAINT fk_ExercicioSerie_Exercicio
    FOREIGN KEY (idExercicio)
    REFERENCES FitnessXtreme.Exercicio (idExercicio)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_ExercicioSerie_Serie
    FOREIGN KEY (idSerie)
    REFERENCES FitnessXtreme.Serie (idSerie)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION) [42102-176]
05-27 15:24:26 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Schema "PUBLIC" cannot be dropped; SQL statement:
drop schema public [90090-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.command.ddl.DropSchema.update(DropSchema.java:45)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:186)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper.executeSQLStatement(SQLExecutionHelper.java:869)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper.access$500(SQLExecutionHelper.java:84)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper$1Loader.run(SQLExecutionHelper.java:145)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
05-27 15:24:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 15:24:51 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 15:24:51 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 15:25:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 15:25:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 15:25:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 15:26:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 15:26:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 15:26:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 15:27:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 15:27:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 15:27:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 16:06:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 16:06:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 16:06:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
