05-27 14:26:24 jdbc[3]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.message.DbException.get(DbException.java:143)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:74)
	at org.netbeans.modules.db.explorer.DbDriverManager.getConnection(DbDriverManager.java:131)
	at org.netbeans.modules.db.explorer.DatabaseConnection.doConnect(DatabaseConnection.java:904)
	at org.netbeans.modules.db.explorer.DatabaseConnection.access$200(DatabaseConnection.java:103)
	at org.netbeans.modules.db.explorer.DatabaseConnection$3.run(DatabaseConnection.java:970)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	... 13 more
05-27 14:27:33 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:27:33 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:27:33 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:27:37 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:28:15 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "USE[*] FITNESSXTREME "; expected "UPDATE, {"; SQL statement:
USE FitnessXtreme [42001-176]
05-27 14:28:36 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Schema "FITNESSXTREME" already exists; SQL statement:
CREATE SCHEMA FitnessXtreme [90078-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.command.ddl.CreateSchema.update(CreateSchema.java:49)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:186)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper.executeSQLStatement(SQLExecutionHelper.java:869)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper.access$500(SQLExecutionHelper.java:84)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper$1Loader.run(SQLExecutionHelper.java:145)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
05-27 14:28:49 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:28:49 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:28:49 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:28:50 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:08 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:08 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:08 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:08 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:08 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:11 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:12 jdbc[6]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:101)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:119)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:74)
	at org.netbeans.modules.db.explorer.DbDriverManager.getConnection(DbDriverManager.java:131)
	at org.netbeans.modules.db.explorer.DatabaseConnection.doConnect(DatabaseConnection.java:904)
	at org.netbeans.modules.db.explorer.DatabaseConnection.access$200(DatabaseConnection.java:103)
	at org.netbeans.modules.db.explorer.DatabaseConnection$3.run(DatabaseConnection.java:970)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.message.DbException.get(DbException.java:143)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:74)
	at org.netbeans.modules.db.explorer.DbDriverManager.getConnection(DbDriverManager.java:131)
	at org.netbeans.modules.db.explorer.DatabaseConnection.doConnect(DatabaseConnection.java:904)
	at org.netbeans.modules.db.explorer.DatabaseConnection.access$200(DatabaseConnection.java:103)
	at org.netbeans.modules.db.explorer.DatabaseConnection$3.run(DatabaseConnection.java:970)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	... 13 more
05-27 14:29:35 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:35 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:35 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:35 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:36 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:36 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:36 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:56 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:56 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:56 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:58 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:29:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 14:48:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unknown data type: "FK_AULAUSUARIO_IDX"; SQL statement:
CREATE TABLE  FitnessXtreme.Aula (
  idAula INT NOT NULL,
  Objetivo VARCHAR(200) NOT NULL,
  descAula VARCHAR(100),
  Usuario_idUsuario INT NOT NULL,
  dataInicioSerie DATE NOT NULL,
  dataFimSerie DATE NOT NULL,
  observacao VARCHAR(200) NOT NULL,
  dataAula DATE NOT NULL,
  repetirToda VARCHAR(50) NOT NULL,
  tempoEsteira VARCHAR(10),
  tempoBicicleta VARCHAR(10),
  tempoElipticon VARCHAR(10),
  PRIMARY KEY (idAula),
  INDEX fk_AulaUsuario_idx (Usuario_idUsuario ASC),
  CONSTRAINT fk_AulaUsuario
    FOREIGN KEY (Usuario_idUsuario)
    REFERENCES FitnessXtreme.Usuario (idUsuario)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION) [50004-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:3963)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3826)
	at org.h2.command.Parser.parseCreateTable(Parser.java:5723)
	at org.h2.command.Parser.parseCreate(Parser.java:4122)
	at org.h2.command.Parser.parsePrepared(Parser.java:351)
	at org.h2.command.Parser.parse(Parser.java:306)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.prepareCommand(Parser.java:243)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper.executeSQLStatement(SQLExecutionHelper.java:869)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper.access$500(SQLExecutionHelper.java:84)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper$1Loader.run(SQLExecutionHelper.java:145)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
05-27 14:48:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unknown data type: "FK_EXERCICIO_GURPOEXERCICIO_IDX"; SQL statement:
CREATE TABLE  FitnessXtreme.Exercicio (
  idExercicio INT NOT NULL,
  nomeExercicio VARCHAR(100) NOT NULL,
  GurpoExercicio_idGurpoExercicio INT NOT NULL,
  PRIMARY KEY (idExercicio),
  INDEX fk_Exercicio_GurpoExercicio_idx (GurpoExercicio_idGurpoExercicio ASC),
  CONSTRAINT fk_Exercicio_GurpoExercicio
    FOREIGN KEY (GurpoExercicio_idGurpoExercicio)
    REFERENCES FitnessXtreme.GurpoExercicio (idGurpoExercicio)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION) [50004-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:3963)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3826)
	at org.h2.command.Parser.parseCreateTable(Parser.java:5723)
	at org.h2.command.Parser.parseCreate(Parser.java:4122)
	at org.h2.command.Parser.parsePrepared(Parser.java:351)
	at org.h2.command.Parser.parse(Parser.java:306)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.prepareCommand(Parser.java:243)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper.executeSQLStatement(SQLExecutionHelper.java:869)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper.access$500(SQLExecutionHelper.java:84)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper$1Loader.run(SQLExecutionHelper.java:145)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
05-27 14:48:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unknown data type: "FK_EXERCICIOPESO_PESO_IDX"; SQL statement:
CREATE TABLE  FitnessXtreme.ExercicioPeso (
  idExercicio INT NOT NULL,
  idPeso INT NOT NULL,
  PRIMARY KEY (idExercicio, idPeso),
  INDEX fk_ExercicioPeso_Peso_idx (idPeso ASC),
  INDEX fk_ExercicioPeso_Exercicio_idx (idExercicio ASC),
  CONSTRAINT fk_ExercicioPeso_Exercicio
    FOREIGN KEY (idExercicio)
    REFERENCES FitnessXtreme.Exercicio (idExercicio)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_ExercicioPeso_Peso
    FOREIGN KEY (idPeso)
    REFERENCES FitnessXtreme.Peso (idPeso)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION) [50004-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:3963)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3826)
	at org.h2.command.Parser.parseCreateTable(Parser.java:5723)
	at org.h2.command.Parser.parseCreate(Parser.java:4122)
	at org.h2.command.Parser.parsePrepared(Parser.java:351)
	at org.h2.command.Parser.parse(Parser.java:306)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.prepareCommand(Parser.java:243)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper.executeSQLStatement(SQLExecutionHelper.java:869)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper.access$500(SQLExecutionHelper.java:84)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper$1Loader.run(SQLExecutionHelper.java:145)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
05-27 14:48:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unknown data type: "FK_EXERCICIOSERIE_SERIE_IDX"; SQL statement:
CREATE TABLE  FitnessXtreme.ExercicioSerie (
  idExercicio INT NOT NULL,
  idSerie INT NOT NULL,
  PRIMARY KEY (idExercicio, idSerie),
  INDEX fk_ExercicioSerie_Serie_idx (idSerie ASC),
  INDEX fk_ExercicioSerie_Exercicio_idx (idExercicio ASC),
  CONSTRAINT fk_ExercicioSerie_Exercicio
    FOREIGN KEY (idExercicio)
    REFERENCES FitnessXtreme.Exercicio (idExercicio)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_ExercicioSerie_Serie
    FOREIGN KEY (idSerie)
    REFERENCES FitnessXtreme.Serie (idSerie)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION) [50004-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:3963)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3826)
	at org.h2.command.Parser.parseCreateTable(Parser.java:5723)
	at org.h2.command.Parser.parseCreate(Parser.java:4122)
	at org.h2.command.Parser.parsePrepared(Parser.java:351)
	at org.h2.command.Parser.parse(Parser.java:306)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.prepareCommand(Parser.java:243)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper.executeSQLStatement(SQLExecutionHelper.java:869)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper.access$500(SQLExecutionHelper.java:84)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper$1Loader.run(SQLExecutionHelper.java:145)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
05-27 14:48:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unknown data type: "FK_AULAEXERCICIO_EXERCICIO_IDX"; SQL statement:
CREATE TABLE  FitnessXtreme.AulaExercicio (
  idAula INT NOT NULL,
  idExercicio INT NOT NULL,
  PRIMARY KEY (idAula, idExercicio),
  INDEX fk_AulaExercicio_Exercicio_idx (idExercicio ASC),
  INDEX fk_AulaExercicio_Aula_idx (idAula ASC),
  CONSTRAINT fk_AulaExercicio_Aula
    FOREIGN KEY (idAula)
    REFERENCES FitnessXtreme.Aula (idAula)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_AulaExercicio_Exercicio
    FOREIGN KEY (idExercicio)
    REFERENCES FitnessXtreme.Exercicio (idExercicio)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION) [50004-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:3963)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3826)
	at org.h2.command.Parser.parseCreateTable(Parser.java:5723)
	at org.h2.command.Parser.parseCreate(Parser.java:4122)
	at org.h2.command.Parser.parsePrepared(Parser.java:351)
	at org.h2.command.Parser.parse(Parser.java:306)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.prepareCommand(Parser.java:243)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper.executeSQLStatement(SQLExecutionHelper.java:869)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper.access$500(SQLExecutionHelper.java:84)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper$1Loader.run(SQLExecutionHelper.java:145)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
05-27 14:49:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "FITNESSXTREME" not found; SQL statement:
drop TABLE FITNESSXTREME [42102-176]
05-27 14:52:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "CREATE TABLE  FITNESSXTREME.USUARIO (
  IDUSUARIO INT NOT NULL,
  NOME VARCHAR(100) NOT NULL,
  MATRICULA INT NOT NULL,
  DATANASCIMENTO DATE NOT NULL,
  CPF VARCHAR(45),
  INDICADORDIREITO VARCHAR(1000) NOT NULL,
  INDICADORESQUERDO VARCHAR(1000) NOT NULL,
  SENHA VARCHAR(50),
  DATACADASTRAMENTO DATE NOT NULL,
  EADMINISTRADOR SMALLINT(1) NOT NULL,
  PRIMARY KEY (IDUSUARIO) "; expected "INDEX, ,, )"; SQL statement:
CREATE TABLE  FitnessXtreme.Usuario (
  idUsuario INT NOT NULL,
  nome VARCHAR(100) NOT NULL,
  matricula INT NOT NULL,
  dataNascimento DATE NOT NULL,
  cpf VARCHAR(45),
  indicadorDireito VARCHAR(1000) NOT NULL,
  indicadorEsquerdo VARCHAR(1000) NOT NULL,
  senha VARCHAR(50),
  dataCadastramento DATE NOT NULL,
  eAdministrador SMALLINT(1) NOT NULL,
  PRIMARY KEY (idUsuario) [42001-176]
05-27 14:52:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USUARIO" not found; SQL statement:
CREATE TABLE  FitnessXtreme.Aula (
  idAula INT NOT NULL,
  Objetivo VARCHAR(200) NOT NULL,
  descAula VARCHAR(100),
  Usuario_idUsuario INT NOT NULL,
  dataInicioSerie DATE NOT NULL,
  dataFimSerie DATE NOT NULL,
  observacao VARCHAR(200) NOT NULL,
  dataAula DATE NOT NULL,
  repetirToda VARCHAR(50) NOT NULL,
  tempoEsteira VARCHAR(10),
  tempoBicicleta VARCHAR(10),
  tempoElipticon VARCHAR(10),
  PRIMARY KEY (idAula),  
  CONSTRAINT fk_AulaUsuario
    FOREIGN KEY (Usuario_idUsuario)
    REFERENCES FitnessXtreme.Usuario (idUsuario)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION) [42102-176]
05-27 14:52:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "AULA" not found; SQL statement:
CREATE TABLE  FitnessXtreme.AulaExercicio (
  idAula INT NOT NULL,
  idExercicio INT NOT NULL,
  PRIMARY KEY (idAula, idExercicio),
  CONSTRAINT fk_AulaExercicio_Aula
    FOREIGN KEY (idAula)
    REFERENCES FitnessXtreme.Aula (idAula)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_AulaExercicio_Exercicio
    FOREIGN KEY (idExercicio)
    REFERENCES FitnessXtreme.Exercicio (idExercicio)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION) [42102-176]
05-27 15:19:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "EXERCICIO" not found; SQL statement:
CREATE TABLE  FitnessXtreme.ExercicioSerie (
  idExercicio INT NOT NULL AUTO_INCREMENT,
  idSerie INT NOT NULL,
  PRIMARY KEY (idExercicio, idSerie),
  CONSTRAINT fk_ExercicioSerie_Exercicio
    FOREIGN KEY (idExercicio)
    REFERENCES FitnessXtreme.Exercicio (idExercicio)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_ExercicioSerie_Serie
    FOREIGN KEY (idSerie)
    REFERENCES FitnessXtreme.Serie (idSerie)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION) [42102-176]
05-27 15:20:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "EXERCICIO" not found; SQL statement:
CREATE TABLE  FitnessXtreme.ExercicioSerie (
  idExercicio INT NOT NULL AUTO_INCREMENT,
  idSerie INT NOT NULL,
  PRIMARY KEY (idExercicio, idSerie),
  CONSTRAINT fk_ExercicioSerie_Exercicio
    FOREIGN KEY (idExercicio)
    REFERENCES FitnessXtreme.Exercicio (idExercicio)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_ExercicioSerie_Serie
    FOREIGN KEY (idSerie)
    REFERENCES FitnessXtreme.Serie (idSerie)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION) [42102-176]
05-27 15:24:26 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Schema "PUBLIC" cannot be dropped; SQL statement:
drop schema public [90090-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.command.ddl.DropSchema.update(DropSchema.java:45)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:186)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper.executeSQLStatement(SQLExecutionHelper.java:869)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper.access$500(SQLExecutionHelper.java:84)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper$1Loader.run(SQLExecutionHelper.java:145)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
05-27 15:24:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 15:24:51 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 15:24:51 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 15:25:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 15:25:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 15:25:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 15:26:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 15:26:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 15:26:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 15:27:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 15:27:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 15:27:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 16:06:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 16:06:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-27 16:06:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-29 11:40:39 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-29 11:40:39 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
05-29 11:40:39 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-01 15:05:45 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DROP FITNESSXTREME[*] "; expected "TABLE, INDEX, USER, SEQUENCE, CONSTANT, TRIGGER, VIEW, ROLE, ALIAS, SCHEMA, ALL, DOMAIN, TYPE, DATATYPE, AGGREGATE"; SQL statement:
drop fitnessxtreme [42001-176]
06-01 16:10:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-01 16:10:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-01 16:10:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-01 16:42:45 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-01 16:42:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-01 16:42:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-01 16:42:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 12:56:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 12:56:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 12:56:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 12:58:07 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 12:58:08 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 12:58:08 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 12:58:08 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 13:01:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 13:01:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 13:01:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 13:05:05 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 13:05:05 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 13:05:05 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 13:05:05 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 13:08:16 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 13:08:16 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 13:08:16 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 15:02:09 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 15:02:09 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 15:02:09 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 15:02:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 15:02:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 15:02:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 15:02:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 15:02:58 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 15:02:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 15:02:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 15:02:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 15:03:07 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 15:03:07 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 15:03:07 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 15:03:08 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 15:03:16 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 15:03:16 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 15:03:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 15:03:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 15:03:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 15:03:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 15:03:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 15:03:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 15:03:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 15:03:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 15:03:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 15:03:22 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 15:03:22 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 15:03:22 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 17:48:07 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 17:48:07 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 17:48:07 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 17:49:16 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 17:49:20 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 17:49:20 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 17:49:20 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 23:23:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 23:23:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 23:23:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 23:23:39 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 23:23:41 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 23:23:41 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-02 23:23:41 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-03 11:16:50 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "CAIXA" not found; SQL statement:
UPDATE FITNESSXTREME.Caixa SET matricula=?, indicadorDireito=?, indicadorEsquerdo=?, senha=?, objetivo=?, nome=?, observacao=?, dataCadastramento=?, eAdministrador=?, dataNascimento=? WHERE idUsuario=? [42102-176]
06-03 12:38:15 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "U" not found; SQL statement:
SELECT * FROM u FITNESSXTREME.Usuario u ORDER BY u.matricula [42102-176]
06-03 15:44:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-03 15:44:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-03 15:44:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-03 15:45:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-03 15:45:26 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-03 15:45:26 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-03 15:45:26 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-03 16:43:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-03 16:43:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-03 16:43:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-04 11:02:58 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-04 11:02:58 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-04 11:02:58 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-04 16:04:44 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-04 16:04:44 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-04 16:04:44 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-05 01:16:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-05 01:16:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-05 01:16:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-05 14:59:37 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-05 14:59:37 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-05 14:59:37 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-05 14:59:51 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-05 15:13:04 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-05 15:13:04 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-05 15:13:04 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-05 15:39:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-05 15:39:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-05 15:39:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-05 15:44:52 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-05 15:45:18 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-05 15:45:18 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-05 15:45:18 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-05 16:19:11 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-05 16:26:52 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-05 16:26:52 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-05 16:26:52 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-05 23:11:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-05 23:11:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-05 23:11:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-05 23:56:52 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-05 23:58:22 jdbc[10]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-05 23:58:22 jdbc[10]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-05 23:58:22 jdbc[10]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-06 00:09:14 jdbc[10]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-06 00:15:25 jdbc[17]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-06 00:15:25 jdbc[17]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-06 00:15:25 jdbc[17]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-06 00:27:40 jdbc[17]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-06 00:28:11 jdbc[21]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-06 00:28:11 jdbc[21]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-06 00:28:11 jdbc[21]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-06 20:33:17 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "EXERCICIO" not found; SQL statement:
SELECT e.nomeExercicio, ae.serie, ae.quantidade, ae.peso FROM Exercicio AS e JOIN AulaExercicio AS ae ON e.idExercicio = ae.idExercicio JOIN Aula AS a ON ae.idAula = a.idAula WHERE a.idAula=1 [42102-176]
06-06 20:35:39 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-06 20:35:39 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-06 20:35:39 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-07 02:09:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-07 02:11:00 jdbc[47]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-07 02:11:00 jdbc[47]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-07 02:11:00 jdbc[47]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-07 02:14:04 jdbc[47]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-07 02:14:55 jdbc[52]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-07 02:14:55 jdbc[52]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-07 02:14:55 jdbc[52]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-07 19:24:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-07 19:24:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-07 19:24:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-19 12:57:33 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Column count does not match; SQL statement:
INSERT INTO BANCO.FITNESSXTREME.EXERCICIO (NOMEEXERCICIO) 
	VALUES ('Supino',1) [21002-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.message.DbException.get(DbException.java:143)
	at org.h2.command.dml.Insert.prepare(Insert.java:266)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper.executeSQLStatement(SQLExecutionHelper.java:869)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper.access$500(SQLExecutionHelper.java:84)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper$1Loader.run(SQLExecutionHelper.java:145)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
06-19 13:11:02 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Column "Supino Inclinado" not found; SQL statement:
INSERT INTO BANCO.FITNESSXTREME.EXERCICIO (NOMEEXERCICIO, IDGRUPO) 
	
 VALUES ("Supino Inclinado",1),
        ("Supino Declinado",1),
        ("Voador",1),
        ("Crucifixo",1),
        ("Crucifixo Inclinado",1),
        ("Cross Over",1) [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Insert.prepare(Insert.java:271)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper.executeSQLStatement(SQLExecutionHelper.java:869)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper.access$500(SQLExecutionHelper.java:84)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper$1Loader.run(SQLExecutionHelper.java:145)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
06-19 13:35:08 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-19 13:35:08 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-19 13:35:08 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-19 21:22:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-19 21:22:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-19 21:22:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-19 23:43:25 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-19 23:43:25 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
06-19 23:43:25 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-176]
